# Generated by Django 3.1.7 on 2021-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='speed_index',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='time_to_interactive',
            field=models.CharField(max_length=50),
        ),
    ]
